import Darwin
import Foundation
import MergeCueCore

/// Opens a `.command` script in a new Terminal window. Injectable so tests never launch Terminal.
public protocol TerminalOpening: Sendable {
    func open(script: URL) async throws
}

/// `/usr/bin/open -a Terminal <script>`: Terminal runs the script in a **new** window; existing sessions are never
/// reused or typed into.
public struct SystemTerminalOpener: TerminalOpening {
    private let runner: any ProcessRunning
    private let timeout: TimeInterval

    public init(runner: any ProcessRunning = ProcessRunner(), timeout: TimeInterval = 15) {
        self.runner = runner
        self.timeout = timeout
    }

    /// The exact argv used.
    public static func arguments(for script: URL) -> [String] {
        ["-a", "Terminal", MergeCuePaths.fileSystemPath(script)]
    }

    public func open(script: URL) async throws {
        let result = try await runner.run(
            URL(filePath: "/usr/bin/open"),
            arguments: Self.arguments(for: script),
            environment: ProcessInfo.processInfo.environment,
            currentDirectory: nil,
            timeout: timeout
        )
        guard result.succeeded else {
            throw AgentLauncherError.openFailed(SecretRedactor.redact(result.stderr.trimmingCharacters(in: .whitespacesAndNewlines)))
        }
    }
}

/// Errors from `AgentLauncher`.
public enum AgentLauncherError: Error, Sendable, Equatable, LocalizedError {
    case invalidCommand(String)
    case scriptWriteFailed(String)
    case openFailed(String)

    public var errorDescription: String? {
        switch self {
        case .invalidCommand(let detail): "Refusing to launch: \(detail)."
        case .scriptWriteFailed(let detail): "Could not write the handoff script: \(detail)."
        case .openFailed(let detail): "Terminal could not open the handoff script. \(detail)"
        }
    }
}

/// Launches a handoff command in a fresh Terminal window through a private `.command` script.
public struct AgentLauncher: Sendable {
    /// Scripts older than this are pruned from the handoff directory on each launch.
    public var retention: TimeInterval
    private let opener: any TerminalOpening
    private let now: @Sendable () -> Date

    public init(
        opener: any TerminalOpening = SystemTerminalOpener(),
        retention: TimeInterval = 24 * 60 * 60,
        now: @escaping @Sendable () -> Date = { Date() }
    ) {
        self.opener = opener
        self.retention = retention
        self.now = now
    }

    /// Script body for `command`: a login zsh (same `PATH` the detector saw) running exactly one command line.
    public static func scriptContents(for command: HandoffCommand, createdAt: Date) -> String {
        let stamp = createdAt.formatted(.iso8601)
        return """
            #!/bin/zsh -l
            # Generated by MergeCue for task \(command.taskID.rawValue) (\(command.agent.displayName)) at \(stamp).
            # Opens the agent in the task's checkout. Safe to delete.
            \(command.shellCommand)

            """
    }

    /// Writes a 0700 `.command` script into `handoffDir` (created 0700 if needed) and opens it in a new Terminal
    /// window. Returns the script URL.
    @discardableResult
    public func openInTerminal(command: HandoffCommand, handoffDir: URL) async throws -> URL {
        guard command.shellCommand == (try? HandoffCommandBuilder.command(
            agent: command.agent, taskID: command.taskID, worktree: command.worktree, executable: command.executable
        ))?.shellCommand else {
            throw AgentLauncherError.invalidCommand("the command was not produced by HandoffCommandBuilder")
        }
        let script = try writeScript(for: command, in: handoffDir)
        try await opener.open(script: script)
        return script
    }

    /// `openInTerminal(command:handoffDir:)` with `MergeCuePaths.handoff`.
    @discardableResult
    public func openInTerminal(command: HandoffCommand, paths: MergeCuePaths) async throws -> URL {
        try await openInTerminal(command: command, handoffDir: paths.handoff)
    }

    /// Writes the script without opening it (also used by `openInTerminal`).
    public func writeScript(for command: HandoffCommand, in handoffDir: URL) throws -> URL {
        let directory = MergeCuePaths.fileSystemPath(handoffDir)
        try Self.ensurePrivateDirectory(directory)
        prune(directory)

        let created = now()
        let stamp = Self.timestamp(created)
        let random = String(UInt32.random(in: 0...UInt32.max), radix: 36)
        let name = "mergecue-\(command.taskID.rawValue)-\(command.agent.slug)-\(stamp)-\(random).command"
        let path = directory + "/" + name
        let data = Array(Self.scriptContents(for: command, createdAt: created).utf8)

        let fd = Darwin.open(path, O_WRONLY | O_CREAT | O_EXCL | O_NOFOLLOW | O_CLOEXEC, 0o700)
        guard fd >= 0 else { throw AgentLauncherError.scriptWriteFailed(String(cString: strerror(errno))) }
        defer { close(fd) }
        var offset = 0
        while offset < data.count {
            let written = data[offset...].withUnsafeBytes { write(fd, $0.baseAddress, $0.count) }
            guard written > 0 else {
                let message = String(cString: strerror(errno))
                unlink(path)
                throw AgentLauncherError.scriptWriteFailed(message)
            }
            offset += written
        }
        guard fchmod(fd, 0o700) == 0 else { throw AgentLauncherError.scriptWriteFailed(String(cString: strerror(errno))) }
        return URL(filePath: path)
    }

    // MARK: Helpers

    static func timestamp(_ date: Date) -> String {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = TimeZone(identifier: "UTC") ?? .gmt
        let c = calendar.dateComponents([.year, .month, .day, .hour, .minute, .second], from: date)
        return String(
            format: "%04d%02d%02dT%02d%02d%02dZ",
            c.year ?? 0, c.month ?? 0, c.day ?? 0, c.hour ?? 0, c.minute ?? 0, c.second ?? 0
        )
    }

    static func ensurePrivateDirectory(_ path: String) throws {
        var info = stat()
        if lstat(path, &info) == 0 {
            guard (info.st_mode & S_IFMT) == S_IFDIR, info.st_uid == getuid() else {
                throw AgentLauncherError.scriptWriteFailed("\(path) is not a private directory")
            }
        } else {
            do {
                try FileManager.default.createDirectory(atPath: path, withIntermediateDirectories: true, attributes: [.posixPermissions: 0o700])
            } catch {
                throw AgentLauncherError.scriptWriteFailed(error.localizedDescription)
            }
        }
        guard chmod(path, 0o700) == 0 else { throw AgentLauncherError.scriptWriteFailed(String(cString: strerror(errno))) }
    }

    /// Removes our own old `.command` scripts.
    private func prune(_ directory: String) {
        let cutoff = now().addingTimeInterval(-retention)
        let names = (try? FileManager.default.contentsOfDirectory(atPath: directory)) ?? []
        for name in names where name.hasPrefix("mergecue-") && name.hasSuffix(".command") {
            let path = directory + "/" + name
            var info = stat()
            guard lstat(path, &info) == 0, (info.st_mode & S_IFMT) == S_IFREG else { continue }
            let modified = Date(timeIntervalSince1970: TimeInterval(info.st_mtimespec.tv_sec))
            if modified < cutoff { unlink(path) }
        }
    }
}
