import Foundation

/// Contents of the synthetic `acme/payments-api` repository used by demo mode (`DemoRepository`). Small but real:
/// a Swift package that builds and tests, plus the Ruby/TypeScript files the GitLab and Bitbucket fixture comments
/// point at. The PR head adds charge retries — and, at `Sources/Payments/ChargeService.swift:84`, the log line the
/// step-1 GitHub review comment flags ("this logs the full card number"). **Synthetic demo data.**
enum DemoRepositoryFiles {
    /// Files of the base commit (`main`).
    static let base: [String: String] = [
        "README.md": readme,
        "Package.swift": packageManifest,
        "docs/PAYMENTS.md": paymentsDoc,
        "config/app.yml": appConfig,
        "Sources/Payments/Gateway.swift": gateway,
        "Sources/Payments/LegacyAdapter.swift": legacyAdapter,
        "Sources/Payments/ChargeService.swift": chargeServiceBase,
        "Tests/PaymentsTests/ChargeServiceTests.swift": chargeServiceTests,
        "src/payments/charge.rb": chargeRuby,
        "src/payments/refund.rb": refundRuby,
        "src/payments/refund.ts": refundTS,
        "src/payments/currency.ts": currencyTS,
        "src/payments/legacy.ts": legacyTS,
        ".gitignore": ".build/\n.swiftpm/\n*.xcodeproj\nnode_modules/\n",
    ]

    /// Files changed or added by the change request head (#42 / !42).
    static let head: [String: String] = [
        "Sources/Payments/ChargeService.swift": chargeServiceHead,
        "Sources/Payments/RetryPolicy.swift": retryPolicy,
    ]

    /// Line of `chargeServiceHead` the step-1 GitHub comment is anchored to.
    static let flaggedLine = 84

    static let readme = """
        # payments-api (synthetic MergeCue demo repository)

        Charges, refunds and retries for the Acme checkout. This repository is generated by MergeCue demo mode;
        it is not a real project.

        ```sh
        swift build
        swift test
        ```

        """

    static let packageManifest = """
        // swift-tools-version:5.9
        import PackageDescription

        let package = Package(
            name: "PaymentsAPI",
            platforms: [.macOS(.v13)],
            products: [.library(name: "Payments", targets: ["Payments"])],
            targets: [
                .target(name: "Payments"),
                .testTarget(name: "PaymentsTests", dependencies: ["Payments"]),
            ]
        )

        """

    static let paymentsDoc = """
        # Payments

        Charges go through `ChargeService`, which talks to the card gateway.
        Webhooks recieve gateway callbacks and update the ledger.

        """

    static let appConfig = """
        gateway:
          url: https://gateway.example.test
          timout: 30
        retries:
          max: 3

        """

    static let gateway = #"""
        import Foundation

        /// Configuration of the card gateway client.
        public struct GatewayConfiguration: Sendable, Equatable {
            public var baseURL: URL
            public var timeout: TimeInterval

            public init(baseURL: URL, timeout: TimeInterval) {
                self.baseURL = baseURL
                self.timeout = timeout
            }
        }

        /// The card gateway.
        public protocol PaymentGateway: Sendable {
            /// Charges `request`; the same `idempotencyKey` never charges twice.
            func charge(_ request: ChargeRequest, idempotencyKey: String) async throws -> String
        }

        /// Default gateway settings.
        public enum GatewayDefaults {
            public static let baseURL = URL(string: "https://gateway.example.test")!

            /// Seconds before a gateway call times out.
            ///
            /// The gateway SLA answers within 10 seconds; slow responses are retried by `RetryPolicy`.
            /// Keep this in sync with `config/app.yml`.
            public static let configuration = GatewayConfiguration(
                baseURL: baseURL,
                timeout: 30
            )
        }

        """#

    static let legacyAdapter = #"""
        import Foundation

        /// Converts amounts from the legacy checkout (decimal dollars) to cents.
        public enum LegacyAdapter {
            public static func cents(fromDollars dollars: Double) -> Int {
                Int(dollars * 100)
            }
        }

        """#

    static let chargeServiceBase = #"""
        import Foundation

        /// A card charge request coming from the checkout API.
        public struct ChargeRequest: Sendable, Equatable {
            public var requestID: String
            public var customerID: String
            public var cardNumber: String
            public var amountCents: Int
            public var currency: String

            public init(requestID: String, customerID: String, cardNumber: String, amountCents: Int, currency: String = "USD") {
                self.requestID = requestID
                self.customerID = customerID
                self.cardNumber = cardNumber
                self.amountCents = amountCents
                self.currency = currency
            }
        }

        public enum ChargeError: Error, Equatable {
            case invalidAmount
            case declined(String)
            case gatewayTimeout
        }

        /// Where the service writes operational logs.
        public protocol PaymentLogger: Sendable {
            func info(_ message: String)
        }

        public struct PrintLogger: PaymentLogger {
            public init() {}
            public func info(_ message: String) { print(message) }
        }

        /// Charges cards through the gateway.
        public struct ChargeService: Sendable {
            let gateway: any PaymentGateway
            let logger: any PaymentLogger

            public init(gateway: any PaymentGateway, logger: any PaymentLogger = PrintLogger()) {
                self.gateway = gateway
                self.logger = logger
            }

            public func charge(_ request: ChargeRequest) async throws -> String {
                guard request.amountCents > 0 else { throw ChargeError.invalidAmount }
                return try await gateway.charge(request, idempotencyKey: request.requestID)
            }
        }

        """#

    static let chargeServiceHead = #"""
        import Foundation

        /// A card charge request coming from the checkout API.
        public struct ChargeRequest: Sendable, Equatable {
            public var requestID: String
            public var customerID: String
            public var cardNumber: String
            public var amountCents: Int
            public var currency: String

            public init(requestID: String, customerID: String, cardNumber: String, amountCents: Int, currency: String = "USD") {
                self.requestID = requestID
                self.customerID = customerID
                self.cardNumber = cardNumber
                self.amountCents = amountCents
                self.currency = currency
            }
        }

        public enum ChargeError: Error, Equatable {
            case invalidAmount
            case declined(String)
            case gatewayTimeout
        }

        /// The outcome of a successful charge.
        public struct ChargeReceipt: Sendable, Equatable {
            public var chargeID: String
            /// Gateway calls it took (1 = no retry).
            public var attempts: Int

            public init(chargeID: String, attempts: Int) {
                self.chargeID = chargeID
                self.attempts = attempts
            }
        }

        /// Where the service writes operational logs.
        public protocol PaymentLogger: Sendable {
            func info(_ message: String)
        }

        public struct PrintLogger: PaymentLogger {
            public init() {}
            public func info(_ message: String) { print(message) }
        }

        /// Charges cards through the gateway, retrying gateway timeouts.
        ///
        /// Every attempt of one request reuses the request id as the idempotency key, so a timeout after the gateway
        /// accepted the charge can never charge the customer twice.
        public struct ChargeService: Sendable {
            let gateway: any PaymentGateway
            let retryPolicy: RetryPolicy
            let logger: any PaymentLogger

            public init(
                gateway: any PaymentGateway,
                retryPolicy: RetryPolicy = RetryPolicy(),
                logger: any PaymentLogger = PrintLogger()
            ) {
                self.gateway = gateway
                self.retryPolicy = retryPolicy
                self.logger = logger
            }

            /// Charges `request`, retrying timeouts up to `retryPolicy.maxRetries` times.
            ///
            /// Retries wait `retryPolicy.delayNanoseconds(forAttempt:)` between attempts (exponential backoff).
            /// Declines are never retried: the gateway already answered, so retrying would only repeat the decline.
            ///
            /// - Parameter request: The charge to perform. `requestID` doubles as the idempotency key.
            /// - Returns: The gateway's charge id and the number of attempts it took.
            /// - Throws: `ChargeError.invalidAmount` for non-positive amounts, `ChargeError.gatewayTimeout` when
            ///   every attempt timed out, or the gateway's error.
            public func charge(_ request: ChargeRequest) async throws -> ChargeReceipt {
                guard request.amountCents > 0 else { throw ChargeError.invalidAmount }
                var attempt = 0
                while true {
                    attempt += 1
                    // Operational log line for support: which card, how much, which attempt.
                    let amount = "\(request.amountCents) \(request.currency)"
                    let context = "request \(request.requestID), attempt \(attempt)"
                    logger.info("Charging card \(request.cardNumber) for \(amount) (\(context))")
                    do {
                        let chargeID = try await gateway.charge(request, idempotencyKey: request.requestID)
                        return ChargeReceipt(chargeID: chargeID, attempts: attempt)
                    } catch ChargeError.gatewayTimeout where attempt <= retryPolicy.maxRetries {
                        try await Task.sleep(nanoseconds: retryPolicy.delayNanoseconds(forAttempt: attempt))
                    }
                }
            }
        }

        """#

    static let retryPolicy = #"""
        import Foundation

        /// How often and how fast `ChargeService` retries gateway timeouts.
        public struct RetryPolicy: Sendable, Equatable {
            /// Base delay before the first retry, in milliseconds.
            public var baseDelayMilliseconds: UInt64

            public init(baseDelayMilliseconds: UInt64 = 200) {
                self.baseDelayMilliseconds = baseDelayMilliseconds
            }

            public var maxRetries: Int {
                let maxRetries = 3
                return maxRetries
            }

            /// Exponential backoff: base, 2 × base, 4 × base, …
            public func delayNanoseconds(forAttempt attempt: Int) -> UInt64 {
                let factor = UInt64(1) << UInt64(max(0, min(attempt - 1, 10)))
                return baseDelayMilliseconds * factor * 1_000_000
            }
        }

        """#

    static let chargeServiceTests = #"""
        import XCTest
        @testable import Payments

        final class RecordingLogger: PaymentLogger, @unchecked Sendable {
            private let lock = NSLock()
            private var storage: [String] = []

            var messages: [String] {
                lock.lock()
                defer { lock.unlock() }
                return storage
            }

            func info(_ message: String) {
                lock.lock()
                storage.append(message)
                lock.unlock()
            }
        }

        struct AcceptingGateway: PaymentGateway {
            func charge(_ request: ChargeRequest, idempotencyKey: String) async throws -> String {
                "ch_\(idempotencyKey)"
            }
        }

        final class ChargeServiceTests: XCTestCase {
            func testRejectsNonPositiveAmounts() async {
                let service = ChargeService(gateway: AcceptingGateway(), logger: RecordingLogger())
                let request = ChargeRequest(requestID: "req_1", customerID: "cus_1", cardNumber: "4242424242424242", amountCents: 0)
                do {
                    _ = try await service.charge(request)
                    XCTFail("expected invalidAmount")
                } catch {
                    XCTAssertEqual(error as? ChargeError, .invalidAmount)
                }
            }
        }

        """#

    static let chargeRuby = """
        # frozen_string_literal: true

        module Payments
          # Charges a card through the gateway (legacy Ruby worker).
          class Charge
            MAX_ATTEMPTS = 5

            def initialize(gateway:, logger:)
              @gateway = gateway
              @logger = logger
            end

            def call(params)
              amount_cents = params.fetch(:amount_cents).to_i
              attempts = 0
              begin
                attempts += 1
                @gateway.charge(amount_cents: amount_cents, idempotency_key: params.fetch(:request_id))
              rescue Gateway::Timeout
                retry if attempts < MAX_ATTEMPTS
                raise
              end
            end
          end
        end

        """

    static let refundRuby = """
        # frozen_string_literal: true

        module Payments
          # Refunds a captured charge.
          class Refund
            def initialize(gateway:, ledger:)
              @gateway = gateway
              @ledger = ledger
            end

            def call(charge_id:, amount_cents:)
              @gateway.refund(charge_id: charge_id, amount_cents: amount_cents)
            end
          end
        end

        """

    static let refundTS = """
        import { Gateway } from "./gateway";

        export interface RefundRequest {
          chargeId: string;
          amountCents: number;
          capturedCents: number;
        }

        export class RefundService {
          constructor(private readonly gateway: Gateway) {}

          async refund(request: RefundRequest): Promise<boolean> {
            if (request.amountCents <= 0) {
              throw new Error("Refund amount must be positive");
            }
            try {
              await this.gateway.refund(request.chargeId, request.amountCents);
              return true;
            } catch (error) {
              return true;
            }
          }
        }

        """

    static let currencyTS = """
        export function toMinorUnits(amount: number): number {
          const minorUnits = Math.floor(amount * 100);
          return minorUnits;
        }

        """

    static let legacyTS = """
        // Legacy refund path, kept for the v1 API.
        export function legacyRefundCents(amount: number): number {
          return Math.trunc(amount * 100);
        }

        """
}
